/**
 * Tests for custom marked renderer configuration.
 *
 * Verifies that all marked.use() renderers compose correctly:
 * - Checkboxes are enabled (no disabled attribute)
 * - Heading IDs are generated by gfmHeadingId
 * - External links open in new tabs
 */

import { marked } from 'marked';
import { gfmHeadingId } from 'marked-gfm-heading-id';

// Apply the same renderer configuration as web-server.js
marked.use(gfmHeadingId());

// Checkbox renderer (must compose with gfmHeadingId, not replace it)
marked.use({
  renderer: {
    checkbox({ checked }) {
      return `<input type="checkbox" class="task-checkbox"${checked ? ' checked' : ''}> `;
    }
  }
});

describe('Marked renderer composition', () => {
  test('checkboxes are enabled (no disabled attribute)', () => {
    const html = marked.parse('- [x] done\n- [ ] todo');
    // Should have task-checkbox class
    expect(html).toContain('class="task-checkbox"');
    // Should NOT have disabled attribute
    expect(html).not.toContain('disabled');
  });

  test('checked checkbox has checked attribute', () => {
    const html = marked.parse('- [x] done');
    expect(html).toContain('checked');
    expect(html).toContain('class="task-checkbox"');
  });

  test('unchecked checkbox does not have checked attribute', () => {
    const html = marked.parse('- [ ] todo');
    expect(html).toContain('class="task-checkbox"');
    // The input tag itself should not contain "checked"
    const inputMatch = html.match(/<input[^>]*>/);
    expect(inputMatch).toBeTruthy();
    expect(inputMatch[0]).not.toContain('checked');
  });

  test('heading IDs are generated despite checkbox renderer', () => {
    const html = marked.parse('## Australia\n\nSome content');
    expect(html).toMatch(/<h2 id="australia">Australia<\/h2>/);
  });

  test('both features work in the same document', () => {
    const html = marked.parse('## Tasks\n\n- [x] done\n- [ ] todo');
    // Heading ID present
    expect(html).toMatch(/<h2 id="tasks">Tasks<\/h2>/);
    // Checkboxes enabled
    expect(html).toContain('class="task-checkbox"');
    expect(html).not.toContain('disabled');
  });
});
